platformName=iOS
platformVersion=12.1
deviceName=iPad Pro (12.9-inch)
deviceType=ipad
udid=872E11BA-9CB0-46FC-9FF8-09A14420D8D5
#udid=9C25B7F1-CDFA-46A0-A8A9-84AF70C476B9
bundleId=gov.uscourts.ambbriefcase-beta
#xcodeOrgId=C27P8NCFQX
xcodeOrgId=U668BW448Y
xcodeSigningId=iPhone Developer
host=http://127.0.0.1:4723/wd/hub
browserName=safari
autoAcceptAlerts=true
safariOpenLinksInBackground=false
safariAllowPopups=true
takes_screehshot=true
ensureCleanSession=true
remotewebdriver.url=http://156.119.24.58:4723/wd/hub
userName=SysadminKasabolotova
password=Asalta6268!Z
platformName_w=Windows 10
deviceName_w=SALTANAMACPC10
app=chrome.exe
remoteHost=http://10.211.55.3:4723/wd/hub
chromeDriver=/Users/saltanakasabolotova/Desktop/driver/chromedriver
chromeDriverKye=webdriver.chrome.driver
copyDelCase=https://cms-ecf-cmka.isso.dcn/cmecf/servlet/CopyDelCase
caseNum=18-83118
singleTableEditor=https://cms-ecf-cmka.isso.dcn/cmecf/servlet/STEditor
dataUpdater=https://cms-ecf-cmka.isso.dcn/cmecf/servlet/MobileBriefcaseDataUpdater
cmecfhelpdeskutility=https://ecf.cmka.aocms.uscourts.gov/CMECFHelpDeskUtility.html
attorneyFillingURL=https://ecf.cmka.aocms.uscourts.gov/
attorneyFirstName=oliveraty
attorneyLastName=Test2013!



duration=2.0
from=600
to=500


COURT_USERS = 3060
COURT_USERS_LINKED_TO_CASE = 3070
PANEL_JUDGES_ONLY = 3128
PANEL_JUDGES_AND_USERs_CHAMBERS = 3118
PANEL_JUDGES_CHAMBERS = 3074
USERs_CHAMBERS = 3127
ONLY_GROUPS_AND_USERS = 3072


-----DB_Credentials-------
sslStore=javax.net.ssl.trustStore
sslLoc=./src/test/resources/certs/cacerts.jks
keyPass=javax.net.ssl.trustStorePassword
Pass=password

dbUrl_CMKA=cmkadb.cmka.aocms.gtwy.dcn
dbUsername_CMKA=ecf_web
dbPwd_CMKA=nE9KrdEngYFX[;
serverName_CMKA=cmka_ssl
databaseName_CMKA=cmka_live
portNumber_CMKA=9089


dbUrl_CM3A=cm3adb.cm3a.aocms.gtwy.dcn
dbUsername_CM3A=ecf_web
dbPwd_CM3A=R5FtfcZyLqEBG
serverName_CM3A=cm3a_ssl
databaseName_CM3A=cm3a_live
portNumber_CM3A=9089

#cmka---ecf_web, nE9KrdEngYFX[; 

#cm3a---ecf_web, R5FtfcZyLqEBG 





STAFF_ATTORNEYS=staffAttorney
BANKRUPTCY_JUDGES=bankruptcyJudges
APPELLATE_JUDGES=appellateJudges

