package gov.uscourts.ao.mobileBriefcase.common;

public enum Actions {

	SORT_DATES_IN_ASCENDING_ORDER, SORT_DATES_IN_DESCENDING_ORDER, SORT_CASES_IN_ASCENDING_ORDER, SORT_CASES_IN_DESCENDING_ORDER,

	/** Referral categories */
	PENDING_TASKS, PETITIONS_FOR_REHEARING, CASES_ON_CALENDAR, MOTIONS_PETITIONS, SCREENING_PANELS,

	/** Panels */
	ASSIGNMENTS, VOTE_INFORMATION, ACTIONS, JUDGMENT_FILED, PETITION_FILED,

	/** Judge's initials */
	SMC, RLW, RWG,

	FILERs_INFORMATION
}
